version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    environment:
      - "discovery.type=single-node"

    networks:
      - global-default

    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana

    ports:
      - 5601:5601

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    depends_on:
      - elasticsearch

    networks:
      - global-default

    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:7.14.0

    depends_on:
      - elasticsearch
      - kibana

    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]

    ports:
      - 8200:8200

    networks:
      - global-default

    environment:
      - apm-server.rum.enabled=true
      - setup.kibana.host=kibana:5601
      - setup.template.settings.index.number_of_replicas=0
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]

    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

volumes:
  elasticsearch-data:
    external: true

networks:
  global-default:
    external: true
