version: '3'

services:

  mysql:
    image: mysql
    container_name: mysql

    networks:
      - global-default

    volumes:
      - ./var/mysql:/var/lib/mysql

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: secret

networks:
  global-default:
    external: true