version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres

    environment:
      POSTGRES_PASSWORD: secret

    ports:
      - 5432:5432

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - global-default

volumes:
  postgres-data:
    external: true

networks:
  global-default:
    external: true