version: '3'

services:

  mysql:
    image: mysql
    container_name: mysql

    networks:
      - global-default

    volumes:
      - mysql-data:/var/lib/mysql

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql-data:
    external: true

networks:
  global-default:
    external: true