version: '3'

services:

  mongo:
    image: mongo
    container_name: mongodb

    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

    volumes:
      - mongodb-data:/data/db

    networks:
      - global-default

  mongoexpress:
    image: mongo-express
    container_name: mongodb_express

    ports:
      - 8081:8081

    depends_on:
      - mongo

    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

    networks:
      - global-default

volumes:
  mongodb-data:
    external: true

networks:
  global-default:
    external: true
