version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - data01:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=secret
      - "discovery.type=single-node"
      - xpack.security.enabled=true

    networks:
      - global-default

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana

    ports:
      - 5601:5601

    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: secret
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

    networks:
      - global-default

    depends_on:
      - elasticsearch

volumes:
  data01:
    driver: local

networks:
  global-default:
    external: true
  